name: Publish Docker

on:
  push:
    branches:
      - saga
  schedule:
    - cron: "0 0 * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          git clone https://github.com/NordicPlayground/fw-nrfconnect-nrf nrf
          cd nrf
          docker build -t coderbyheart/fw-nrfconnect-nrf-docker -f ../Dockerfile .
      - name: Build asset_tracker application
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker; west build -p always -b nrf9160_pca20035ns'
      - name: Publish image
        run: |
          cd nrf
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker images
          docker push coderbyheart/fw-nrfconnect-nrf-docker
