name: Publish Docker

on:
  push:
    - branch: saga
  schedule:
    - cron: "0 0 * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: |
          git clone https://github.com/nrfconnect/sdk-nrf nrf
          cd nrf
          docker build -t coderbyheart/fw-nrfconnect-nrf-docker -f ../Dockerfile .

      - name: Build asset_tracker application
        run: |
          docker run --rm -v ${PWD}/nrf:/workdir/ncs/nrf \
            coderbyheart/fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/nrf/applications/asset_tracker && west build -p always -b nrf9160dk_nrf9160ns'

      - uses: actions/upload-artifact@v2
        with:
          name: asset_tracker
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Publish image
        run: |
          cd nrf
          docker login -u coderbyheart -p $DOCKER_PASSWORD
          docker images
          docker push coderbyheart/fw-nrfconnect-nrf-docker
