name: Verify Dockerfile

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        ncs_branch:
          - main
          - v1.9-branch
          - v1.8-branch
          - v1.7-branch
          - v1.6-branch
          - v1.5-branch
          - v1.4-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t nrfassettracker/nrfconnect-sdk:${{ matrix.ncs_branch }} \
            --build-arg sdk_nrf_revision=${{ matrix.ncs_branch }} .

      - name: Initialize sdk-nrf
        run: |
          docker run --rm -v ${PWD}:/workdir/project \
            nrfassettracker/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west init -m https://github.com/nrfconnect/sdk-nrf --mr ${{ matrix.ncs_branch }}

      - name: Update west dependencies
        run: |
          docker run --rm -v ${PWD}:/workdir/project \
            nrfassettracker/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west update --narrow -o=--depth=1

      - name: Build asset_tracker application
        # Removed in 1.9
        if: matrix.ncs_branch != 'main' && matrix.ncs_branch != 'v1.9-branch'
        run: |
          docker run --rm -v ${PWD}:/workdir/project \
            -w /workdir/project/nrf/applications/asset_tracker \
            nrfassettracker/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west build -b nrf9160dk_nrf9160ns

      - uses: actions/upload-artifact@v2
        with:
          name: asset_tracker-${{ matrix.ncs_branch }}
          path: |
            nrf/applications/asset_tracker/build/zephyr/merged.hex
            nrf/applications/asset_tracker/build/zephyr/app_update.bin

      - name: Build asset_tracker_v2 application
        # Not available in 1.4, and needs configuration in 1.5
        if: matrix.ncs_branch != 'v1.4-branch' && matrix.ncs_branch != 'v1.5-branch'
        run: |
          docker run --rm -v ${PWD}:/workdir/project \
            -w /workdir/project/nrf/applications/asset_tracker_v2 \
            nrfassettracker/nrfconnect-sdk:${{ matrix.ncs_branch }} \
              west build -b nrf9160dk_nrf9160ns

      - uses: actions/upload-artifact@v2
        if: matrix.ncs_branch != 'v1.4-branch' && matrix.ncs_branch != 'v1.5-branch'
        with:
          name: asset_tracker_v2-${{ matrix.ncs_branch }}
          path: |
            nrf/applications/asset_tracker_v2/build/zephyr/merged.hex
            nrf/applications/asset_tracker_v2/build/zephyr/app_update.bin
